spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GREENTECH_DB?useTimezone=true&serverTimezone=UTC
    username: root
    password: Droit*90
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
